# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ERMC Katowice 2027
email: todo@todo.todo
description: >- # this means to ignore newlines until "baseurl:"
  ERMC Katowice 2027
baseurl: "/ermc-website" # the subpath of your site, e.g. /blog
url: "https://polska-liga-mahjonga.github.io"
github_username: Polska-Liga-Mahjonga
repository: Polska-Liga-Mahjonga/ermc-website
logo: /assets/images/logo.svg
og_image: /assets/images/logo.png

social:
  type: Organization
  links:
    - "https://github.com/Polska-Liga-Mahjonga"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related:  

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-archives
  - jekyll-feed

timezone: Europe/Warsaw
search: true

permalink: /:categories/:year/:month/:day/:title/
lang: en

paginate: 10
paginate_path: /page/:num/

facebook:
  app_id:
  publisher: todo.todo

footer:
  links:

jekyll-archives:
  enabled:
    - categories
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

sass:
  sass_dir: _sass
  style: compressed

compress_html:
  clippings: all
  comments: all
  ignore:
    envs: development  # disable compression in dev environment

collections:
  pages:
    output: true
    permalink: /:path/

include:
  - icons/
  - _pages/
exclude:
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor
